name: Release

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'App Version'
        required: true

jobs:
  release:
    runs-on: macos-10.15

    steps:
    # 1) Clone the Repository
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: ${{ github.event.inputs.branch }}

    # 2) Set Environment
    - name: Set Environment
      run: export APP_VERSION="${{ github.event.inputs.app_version }}

    # 3) Build and Upload the App
    - name: Create Release Build
      run: bundle exec fastlane release
